# Set the target Python version
target-version = "py311"

# Enable specific linting rules
select = ["E", "F", "W", "I" , "UP"]

# Maximum line length
line-length = 100

# Fix issues automatically where possible
fix = true

include = ["*.py", "*.ipynb"]

# Ignore errors
ignore = [
    'E203',
    'E731',
    'E741',
    'F722', # conflicts with jaxtyping Array annotations
    'E501'
]
