# Set the target Python version
target-version = "py311"

# Enable specific linting rules
select = ["E", "F", "W", "I" , "UP"]

# Ignore specific rules
ignore = ["E501"]  # Ignore line length issues

# Exclude certain directories
exclude = ["tests", "migrations"]

# Maximum line length
line-length = 88

# Fix issues automatically where possible
fix = true

include = ["*.py", "*.ipynb", "*.md"]

